# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy the Blog

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
  # Runs every day at 00:10 GMT+8 (which is 16:10 UTC)
  schedule:
    - cron: "10 16 * * *"

  # Allows manual execution from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true  # Runs 'bundle install' and caches gems automatically
          cache-version: 0  # Increment if cache needs to be refreshed

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Setup IndexNow
        run: echo "f8fc080f517d4f2e9211d0a276b04282" > indexnow.txt

      - name: Build with Jekyll
        run: bundle install && bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
