name: "IndexNow"
on:
  schedule:
    # 每天北京时间 08:00 和 20:00（对应 UTC 时间 00:00 和 12:00）
    - cron: '0 0,12 * * *'

  # 允许手动触发
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: "https://www.big-yellow-j.top/static/xml/sitemap.xml"
          key: f8fc080f517d4f2e9211d0a276b04282